---
title: C6312 |Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 15
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: 2f33d2a6e7e87f14859614fa25e1bd846764b944
ms.sourcegitcommit: 6cfffa72af599a9d667249caaaa411bb28ea69fd
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 09/02/2020
ms.locfileid: "77273916"
---
# <a name="c6312"></a>C6312
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

警告 C6312：可能的无限循环：在 try 的异常筛选器表达式中使用常量 EXCEPTION_CONTINUE_EXECUTION  
  
 此警告指示在 `EXCEPTION_CONTINUE_EXECUTION` 结构化异常处理程序的筛选器表达式中使用常量 (或另一个计算结果为-1) 的常量。 使用常数值 `EXCEPTION_CONTINUE_EXECUTION` 可能导致无限循环。 例如，如果硬件引发了异常，则会重新启动导致此异常的指令。 如果导致此异常的地址仍错误，则会出现另一个异常，并以相同的方式进行处理。 这将导致无限循环。  
  
 对的显式调用 `RaiseException` 不会直接导致无限循环，但会继续执行受保护的块中的代码。 这可能是意外情况，如果 `RaiseException` 使用它来避免取消引用无效的指针，这可能会导致无限循环。  
  
 通常， `EXCEPTION_CONTINUE_EXECUTION` 仅应由在筛选器表达式中调用的函数返回，该函数有机会修复导致异常的指针或基础内存。  
  
## <a name="example"></a>示例  
 下面的代码将生成此警告：  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 若要更正此警告，请使用以下代码：  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```
