---
title: C26160
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26160
helpviewer_keywords:
- C26160
ms.assetid: e6518687-36b4-4eae-a732-758881638295
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 816a7b05b0809d2c49583bad50ee459d9cae45df
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/16/2019
ms.locfileid: "72450230"
---
# <a name="c26160"></a>C26160
警告 C26160：调用方可能在 > 调用函数 \<func > 之前未能持有锁 \<lock。

 警告 C26160 类似于 warning [C26110](../code-quality/c26110.md) ，只不过置信度较低。 例如，函数可以包含批注错误。

## <a name="example"></a>示例
 下面的代码生成警告 C26160。

```cpp

struct Account
{
    _Guarded_by_(cs) int balance;
    CRITICAL_SECTION cs;

    _No_competing_thread_ void Init()
    {
        balance = 0; // OK
    }

    _Requires_lock_held_(this->cs) void FuncNeedsLock();

    _No_competing_thread_ void FuncInitCallOk()
        // this annotation requires this function is called
        // single-threaded, therefore we don't need to worry
        // about the lock
    {
        FuncNeedsLock(); // OK, single threaded
    }

    void FuncInitCallBad() // No annotation provided, analyzer generates warning
    {
        FuncNeedsLock(); // Warning C26160
    }

};
```

## <a name="example"></a>示例
 下面的代码显示了上一示例的解决方案。

```cpp

struct Account
{
    _Guarded_by_(cs) int balance;
    CRITICAL_SECTION cs;

    _No_competing_thread_ void Init()
    {
        balance = 0; // OK
    }

    _Requires_lock_held_(this->cs) void FuncNeedsLock();

    _No_competing_thread_ void FuncInitCallOk()
        // this annotation requires this function is called
        // single-threaded, therefore we don't need to worry
        // about the lock
    {
        FuncNeedsLock(); // OK, single threaded
    }

    void FuncInitCallBadFixed() // this function now properly acquires (and releases) the lock
    {
        EnterCriticalSection(&this->cs);FuncNeedsLock();LeaveCriticalSection(&this->cs);
    }
};
```
