---
title: C28163
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28163
helpviewer_keywords:
- C28163
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 3e9bd974b38647cd330c55df0b8d0063c77bff52
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/16/2019
ms.locfileid: "72434573"
---
# <a name="c28163"></a>C28163
警告 C28163：绝不应从 try/except 块中调用函数

 当函数的类型不应包含在 `try/except` 块中的 `try/except` 块中时，将报告此警告。 代码分析工具至少发现了一个路径，其中，所调用的函数都位于 `try/except` 块中。
