---
title: C6242
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6242
helpviewer_keywords:
- C6242
ms.assetid: 523d46ce-8370-434c-a752-2e3a18cca9a5
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 69b5761abd02adf16c3c4f3148fcf1218e1a65c5
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 04/23/2019
ms.locfileid: "62578817"
---
# <a name="c6242"></a>C6242
警告 C6242:从此 try 块跳转将强制展开局部堆栈。 会产生严重影响性能

 此警告表明，跳转语句会导致退出受保护的块的的 try-finally 以外的其他通过贯穿的控制流。

 保留受保护的的 try-finally 块其他不是通过从上次故障语句需要本地展开发生。 展开局部堆栈通常需要大约 1000年机器指令;因此，它是对性能造成不利影响。

 使用`_leave`退出受保护的的 try-finally 块。

## <a name="example"></a>示例
 下面的代码生成此警告：

```
#include <malloc.h>
void DoSomething(char *p); // function can throw exception

int f( )
{
   char *ptr = 0;
   __try
   {
      ptr = (char*) malloc(10);
      if ( !ptr )
      {
         return 0;   //Warning: 6242
      }
      DoSomething( ptr );
   }
   __finally
   {
      free( ptr );
   }
   return 1;
}
```

 若要更正此警告，请使用`__leave`如下面的代码中所示：

```
#include <malloc.h>
void DoSomething(char *p);
int f()
{
   char *ptr = 0;
   int retVal = 0;

   __try
   {
      ptr = (char *) malloc(10);
      if ( !ptr )
      {
         retVal = 0;
         __leave;   //No warning
      }
      DoSomething( ptr );
      retVal = 1;
   }
   __finally
   {
      free( ptr );
   }

   return retVal;
}
```

 使用 malloc 和免费有内存泄漏和异常方面的许多缺陷。 若要避免这些类型的泄漏和异常问题完全，使用的机制，通过提供C++标准模板库 (STL)。 其中包括[shared_ptr](/cpp/standard-library/shared-ptr-class)， [unique_ptr](/cpp/standard-library/unique-ptr-class)，并[向量](/cpp/standard-library/vector)。 有关详细信息，请参阅[智能指针](/cpp/cpp/smart-pointers-modern-cpp)并[C++标准库](/cpp/standard-library/cpp-standard-library-reference)。

## <a name="see-also"></a>请参阅
 [try-finally 语句](/cpp/cpp/try-finally-statement)