---
title: C6263
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6263
helpviewer_keywords:
- C6263
ms.assetid: bc360ad7-5f59-4480-a642-6c7e6beeb5f6
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 2f3763eeb67f7ec2da0fc96ba2c2088a84e67e62
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 12/06/2019
ms.locfileid: "74878523"
---
# <a name="c6263"></a>C6263
警告 C6263：在循环中使用 _alloca: 这样会很快造成堆栈溢出

 此警告意味着在循环内调用 _alloca 以分配内存可能导致堆栈溢出。 _alloca 从堆栈中分配内存，但仅在调用函数退出时释放内存。 即使在用户模式下，堆栈也会受到限制，并且未能提交堆栈页会导致堆栈溢出异常。 `_resetstkoflw` 函数将从堆栈溢出条件中恢复，让程序继续执行，而不会出现致命异常错误。 如果未调用 `_resetstkoflw` 函数，则在前一个异常后不会出现任何保护页。 下次发生堆栈溢出时，将不会有任何异常，且进程会在无警告的情况下终止。

 如果分配大小或迭代计数未知，应避免在循环内调用 `_alloca`，因为这可能导致堆栈溢出。 在这些情况下，请考虑其他选项，如、堆内存或[ C++标准库](/cpp/standard-library/cpp-standard-library-reference)类。

## <a name="example"></a>示例
 下面的代码将生成此警告：

```cpp
#include <windows.h>
#include <malloc.h>
#include <excpt.h>
#include <stdio.h>

#define MAX_SIZE 50

void f ( int size )
{
  char* cArray;
  __try
  {
    for(int i = 0; i < MAX_SIZE; i++)
    {
      cArray = (char *)_alloca(size);

     // process cArray...
    }
  }
  __except(GetExceptionCode() == STATUS_STACK_OVERFLOW ?
              EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
     // code...
     puts("Allocation Failed");
    _resetstkoflw();
  }
}
```

 下面的代码使用 malloc （）来更正此警告：

```cpp
#include <windows.h>
#define MAX_SIZE 50

void f ( int size )
{
  char* cArray;

  for(int i = 0; i < MAX_SIZE; i++)
  {
     cArray = (char *) malloc(size);
     if (cArray != NULL)
     {
       // process cArray...
       free(cArray);
     }
  }
}
```

## <a name="see-also"></a>另请参阅

- [malloc](/cpp/c-runtime-library/reference/malloc)
- [_alloca](/cpp/c-runtime-library/reference/alloca)
- [_malloca](/cpp/c-runtime-library/reference/malloca)
- [C++ 标准库](/cpp/standard-library/cpp-standard-library-reference)
