---
title: C6263
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6263
helpviewer_keywords:
- C6263
ms.assetid: bc360ad7-5f59-4480-a642-6c7e6beeb5f6
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 71fc672fb876643d78e69fa8d4d5a24c4af04f5e
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 04/23/2019
ms.locfileid: "62578765"
---
# <a name="c6263"></a>C6263
警告 C6263： 在循环中使用 _alloca这可以快速溢出堆栈

 此警告意味着调用 _alloca 在循环中要分配的内存可能会导致堆栈溢出。 _alloca 堆栈中分配内存，但该调用的函数退出时，才会释放内存。 堆栈，即使在用户模式中的受到限制，并且提交页面堆栈的失败会导致堆栈溢出异常。 `_resetstkoflw` 函数将从堆栈溢出条件中恢复，让程序继续执行，而不会出现致命异常错误。 如果`_resetstkoflw`不调用函数前, 一个异常之后没有任何保护页。 下次发生堆栈溢出时，将不会有任何异常，且进程会在无警告的情况下终止。

 应避免调用`_alloca`如果因为它可能会导致堆栈溢出，分配的大小或迭代次数是未知的循环内。 在这些情况下，请考虑其他选项，例如堆内存，或[C++标准库](/cpp/standard-library/cpp-standard-library-reference)类。

## <a name="example"></a>示例
 下面的代码生成此警告：

```
#include <windows.h>
#include <malloc.h>
#include <excpt.h>
#include <stdio.h>

#define MAX_SIZE 50

void f ( int size )
{
  char* cArray;
  __try
  {
    for(int i = 0; i < MAX_SIZE; i++)
    {
      cArray = (char *)_alloca(size);

     // process cArray...
    }
  }
  __except(GetExceptionCode() == STATUS_STACK_OVERFLOW ?
              EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
     // code...
     puts("Allocation Failed");
    _resetstkoflw();
  }
}
```

 以下代码使用 malloc （） 若要更正此警告：

```
#include <windows.h>
#define MAX_SIZE 50

void f ( int size )
{
  char* cArray;

  for(int i = 0; i < MAX_SIZE; i++)
  {
     cArray = (char *) malloc(size);
     if (cArray != NULL)
     {
       // process cArray...
       free(cArray);
     }
  }
}
```

## <a name="see-also"></a>请参阅

- [malloc](/cpp/c-runtime-library/reference/malloc)
- [_alloca](/cpp/c-runtime-library/reference/alloca)
- [_malloca](/cpp/c-runtime-library/reference/malloca)
- [C++ 标准库](/cpp/standard-library/cpp-standard-library-reference)